# Generated by Django 4.2 on 2023-05-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_lecture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
