# Generated by Django 4.2.1 on 2023-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230522_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectlist',
            old_name='myLect',
            new_name='myLects',
        ),
        migrations.AlterField(
            model_name='lectlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
