# Generated by Django 4.2.1 on 2023-06-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='study',
            name='relateLect',
        ),
        migrations.AddField(
            model_name='study',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='study',
            name='purpose',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='study',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
