# Generated by Django 4.2.1 on 2023-06-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0002_remove_study_participant_remove_study_relatelect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='author',
            field=models.CharField(default='NoNamed', max_length=150),
        ),
        migrations.AddField(
            model_name='study',
            name='title',
            field=models.CharField(default='Empty title', max_length=150),
        ),
    ]
