# Generated by Django 4.2 on 2023-05-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pubDate', models.DateTimeField()),
                ('author', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('pubDate', models.DateTimeField()),
                ('author', models.CharField(max_length=15)),
                ('lectName', models.CharField(max_length=20)),
                ('comments', models.ManyToManyField(to='board.comment')),
            ],
        ),
    ]
