# Generated by Django 4.2.1 on 2023-06-03 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='evalLect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectName', models.CharField(max_length=150)),
                ('professor', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('likeIt', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=15)),
                ('lectName', models.CharField(max_length=20)),
                ('files', models.FileField(blank=True, null=True, upload_to='post_files')),
                ('images', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('font', models.CharField(blank=True, max_length=50)),
                ('fontSize', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.ManyToManyField(to='board.comment')),
                ('likes', models.ManyToManyField(to='board.like')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(to='board.like'),
        ),
    ]
