# Generated by Django 4.2.1 on 2023-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evallect',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
