# Generated by Django 4.2.1 on 2023-06-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_evallect_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='evallect',
            name='author',
            field=models.CharField(default='', max_length=150),
        ),
    ]
