# Generated by Django 4.2.1 on 2023-06-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_evallect_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likeIt',
            field=models.IntegerField(default=0),
        ),
    ]
