# Generated by Django 4.2.1 on 2023-05-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_like_delete_testpost_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(to='board.like'),
        ),
    ]
